<?php
use Drupal\uniplugin\UniPluginHub;

/**
 * @return \Drupal\uniplugin\UniPluginHub
 */
function uniplugin() {
  static $hub;
  return isset($hub)
    ? $hub
    : $hub = new UniPluginHub();
}

/**
 * @param array $form
 * @param array $form_state
 *
 * @return array
 *
 * @see \Drupal\uniplugin\FormElement\UniPluginFormElement::process()
 */
function _uniplugin_element_ajax_callback(array $form, array &$form_state) {
  return $form_state['triggering_element']['#plugin_options_element_reference'];
}
